api_platform:
    enable_swagger_ui: true
    collection:
        pagination:
            enabled: false
    mapping:
        paths: 
            - '%kernel.project_dir%/src/Entity' # default configuration for annotations
            - '%kernel.project_dir%/config/packages/api_platform' # yaml or xml directory configuration
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
             apiKey:
                name: Authorization
                type: header
